# DS2002 · Walmart Warm-Up SKU Mess

**Lab — 2026-10-16 · Fall 2026**  

---

## Lab 08 — Walmart Warm-Up (SKU Mess)

This lab uses the **real midterm data** in `../06-midterm-walmart/data/`. It's a warm-up so you hit the ground running on the project. On Kaggle/Colab, upload the data folder or adjust the path.

*If the file isn't found, the cell falls back to a small inline sample so the notebook still runs.*

In [1]:
import pandas as pd
PATH = '/content/product_catalog.csv'
try:
    cat = pd.read_csv(PATH)
except FileNotFoundError:
    from io import StringIO
    cat = pd.read_csv(StringIO('sku,product_name,category\nPT-12,pop-tarts strawberry,Breakfast Foods\nSKU#459812,Strawberry Pop-Tart,Breakfast\nPOPTART-STRAW,Pop-Tarts Strawberry,Breakfast'))
cat_length = len(cat)
cat

,sku,product_name,category,subcategory,unit_cost,supplier,package_size
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack
4,WTR-24,BOTTLED WATER 24PK,Emergency Supplies,Bottled,2.64,Sara Lee,1 pack
5,WATER24PK,Bottled Water 24-Pack,Emergency,Bottled,2.38,Sara Lee,24 pack
6,WTR_24PK,Water - 24 Pack,Emergency,NaN,2.08,Frito-Lay,1 pack
7,BATT-100,BATTERIES AA 4PK,Emergency Supplies,AA,NaN,3M Company,6 pack
8,BAT-AA4,AA Batteries 4-Pack,Emergency Supplies,AA,4.16,Kimberly-Clark,4pk
9,BATT_AA_4PK,AA Batteries 4-Pack,Emergency,AA,3.71,Anheuser-Busch,24 pack
10,FLASH-01,FLASHLIGHT LED,Emergency,Flashlight,NaN,Frito-Lay,6-pack
11,LED-FLASH,FLASHLIGHT LED,EMERGENCY,NaN,8.20,Frito-Lay,single
12,BEER-24,Light Beer (24-pack),Alcoholic Beverages,NaN,9.62,Hasbro,bundle
13,LTBEER24,Light Beer (24-pack),ALCOHOL,Light,7.61,Kellogg's,bundle
14,BG-MONO,Monopoly Board Game,ENTERTAINMENT,NaN,9.96,Kimberly-Clark,1pk
15,MONOPOLY-01,Monopoly Board Game,entertainment,NaN,12.51,Georgia-Pacific,24-pack
16,GAME-MONO,Board Game - Monopoly,ENTERTAINMENT,NaN,NaN,Campbell's,1pk
17,CARDS-01,Playing Cards,ENTERTAINMENT,Playing,2.45,J.M. Smucker,4pk
18,PLAYCARD-STD,PLAYING CARDS,entertainment,Playing,2.39,Georgia-Pacific,24-pack
19,STREAM-01,Roku Streaming Stick,Electronics,Streaming,16.70,3M Company,12 pack
20,ROKU-STD,Streaming Device,electronics,Streaming,16.99,Anheuser-Busch,12 pack
21,SOUP-CAN,Soup - Canned,Groceries,Canned,1.23,J.M. Smucker,single
22,CNSOUP-01,Canned Soup,GROCERY,NaN,1.19,Generic Supplier,single
23,BREAD-WH,WHITE BREAD,Grocery,Bread,1.53,Procter & Gamble,24-pack
24,WHITEBREAD,WHITE BREAD,grocery,Bread,1.12,Sara Lee,24 pack
25,PB-16,PEANUT BUTTER,GROCERY,Peanut,1.36,Hasbro,bundle
26,PNUTBTR-16,Peanut Butter,GROCERY,Peanut,1.94,Sara Lee,1-pack
27,CNDL-EM,Candles (Emergency),EMERGENCY,Candles,3.81,Frito-Lay,1 pack
28,CANDLE-EMRG,Emergency Candles,EMERGENCY,Candles,3.43,Roku Inc,24pk
29,FAID-01,First-Aid Kit,health,First,6.90,Anheuser-Busch,4 pack
30,FIRSTAID-KIT,First Aid Kit,health,NaN,7.85,J.M. Smucker,4 pack
31,CHRG-PORT,PORTABLE CHARGER,ELECTRONICS,NaN,11.99,Georgia-Pacific,single
32,PORTCHARGER,Portable Phone Charger,ELECTRONICS,Portable,15.03,Johnson & Johnson,12 pack
33,CHIPS-VP,Variety Pack - Chips,snacks,Chips,4.03,Frito-Lay,single
34,CHIPVARIETY,Chips Variety Pack,Snacks,Chips,4.11,Generic Supplier,4-pack
35,PTOWEL-6,Paper Towels,household,Paper,3.85,Campbell's,4 pack
36,PAPERTOWEL6,Paper Towels,HOUSEHOLD,Paper,5.09,Georgia-Pacific,12-pack
37,TP-12,TOILET PAPER 12PK,household,Toilet,5.58,Campbell's,1 pack
38,TOILETPAPER12,Toilet Paper 12-Roll,Household,Toilet,5.75,J.M. Smucker,24-pack
39,DIAP-S3,Baby Diapers - Size 3,baby,Diapers,14.40,Procter & Gamble,single
40,DIAPERS-3,DIAPERS SZ 3,Baby Products,Diapers,13.59,Generic Supplier,6 pack
41,BFORM-01,Infant Formula,Baby,Baby,18.87,Procter & Gamble,4-pack
42,BABYFORMULA,Baby Formula,Baby,NaN,18.25,Sara Lee,6 pack
43,TARP-HD,Heavy Duty Tarp,Emergency,NaN,11.90,J.M. Smucker,12 pack
44,HDTARP-01,TARP - HEAVY DUTY,emergency,Tarp,NaN,J.M. Smucker,24pk

### Q1 — How many rows look like Pop-Tart products?

Filter on `product_name` containing `pop`, case-insensitively. Print the count and the matching rows.

In [2]:
# TODO (hint: .str.lower().str.contains('pop'))
pop_tarts = cat[cat["product_name"].str.contains("pop", case=False, na=False)]

print("count:", len(pop_tarts))
print(pop_tarts)

count: 4
             sku          product_name         category subcategory  \
0          PT-12  pop-tarts strawberry  Breakfast Foods         NaN
1     SKU#459812   Strawberry Pop-Tart        Breakfast   Pop-Tarts
2  POPTART-STRAW  Pop-Tarts Strawberry        Breakfast         NaN
3  PT_STRAWBERRY  pop-tarts strawberry        breakfast   Pop-Tarts

   unit_cost           supplier package_size
0       1.93  Johnson & Johnson       4-pack
1       2.26           Roku Inc          4pk
2       2.11           Sara Lee       6 pack
3        NaN         Campbell's       4 pack

### Q2 — Which SKUs and names all mean *strawberry* Pop-Tart?

List them. Then note which Pop-Tart rows are **not** strawberry — those must stay separate, and saying so is part of the answer.

In [3]:
# TODO
strawberry_pop_tarts = pop_tarts[pop_tarts['product_name'].str.contains('strawberry',case=False,na=False)]
print(strawberry_pop_tarts)
print(strawberry_pop_tarts.equals(pop_tarts))

             sku          product_name         category subcategory  \
0          PT-12  pop-tarts strawberry  Breakfast Foods         NaN
1     SKU#459812   Strawberry Pop-Tart        Breakfast   Pop-Tarts
2  POPTART-STRAW  Pop-Tarts Strawberry        Breakfast         NaN
3  PT_STRAWBERRY  pop-tarts strawberry        breakfast   Pop-Tarts

   unit_cost           supplier package_size
0       1.93  Johnson & Johnson       4-pack
1       2.26           Roku Inc          4pk
2       2.11           Sara Lee       6 pack
3        NaN         Campbell's       4 pack
True

**Pop-Tart rows that are a different product:** None of the Pop-Tart rows are a different product, they are all strawberry pop tarts

### Q3 — Build the mapping

A dict from each variant SKU to one canonical SKU. Then apply it in a way that leaves unmapped SKUs as themselves rather than turning them into `NaN` — that single mistake silently deletes most of the catalog.

In [4]:
# TODO
sku_map = {"SKU#459812": "PT-12","POPTART-STRAW": "PT-12","PT_STRAWBERRY": "PT-12"}
cat["canonical_sku"] = cat["sku"].replace(sku_map)
cat

,sku,product_name,category,subcategory,unit_cost,supplier,package_size,canonical_sku
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack,PT-12
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk,PT-12
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack,PT-12
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack,PT-12
4,WTR-24,BOTTLED WATER 24PK,Emergency Supplies,Bottled,2.64,Sara Lee,1 pack,WTR-24
5,WATER24PK,Bottled Water 24-Pack,Emergency,Bottled,2.38,Sara Lee,24 pack,WATER24PK
6,WTR_24PK,Water - 24 Pack,Emergency,NaN,2.08,Frito-Lay,1 pack,WTR_24PK
7,BATT-100,BATTERIES AA 4PK,Emergency Supplies,AA,NaN,3M Company,6 pack,BATT-100
8,BAT-AA4,AA Batteries 4-Pack,Emergency Supplies,AA,4.16,Kimberly-Clark,4pk,BAT-AA4
9,BATT_AA_4PK,AA Batteries 4-Pack,Emergency,AA,3.71,Anheuser-Busch,24 pack,BATT_AA_4PK
10,FLASH-01,FLASHLIGHT LED,Emergency,Flashlight,NaN,Frito-Lay,6-pack,FLASH-01
11,LED-FLASH,FLASHLIGHT LED,EMERGENCY,NaN,8.20,Frito-Lay,single,LED-FLASH
12,BEER-24,Light Beer (24-pack),Alcoholic Beverages,NaN,9.62,Hasbro,bundle,BEER-24
13,LTBEER24,Light Beer (24-pack),ALCOHOL,Light,7.61,Kellogg's,bundle,LTBEER24
14,BG-MONO,Monopoly Board Game,ENTERTAINMENT,NaN,9.96,Kimberly-Clark,1pk,BG-MONO
15,MONOPOLY-01,Monopoly Board Game,entertainment,NaN,12.51,Georgia-Pacific,24-pack,MONOPOLY-01
16,GAME-MONO,Board Game - Monopoly,ENTERTAINMENT,NaN,NaN,Campbell's,1pk,GAME-MONO
17,CARDS-01,Playing Cards,ENTERTAINMENT,Playing,2.45,J.M. Smucker,4pk,CARDS-01
18,PLAYCARD-STD,PLAYING CARDS,entertainment,Playing,2.39,Georgia-Pacific,24-pack,PLAYCARD-STD
19,STREAM-01,Roku Streaming Stick,Electronics,Streaming,16.70,3M Company,12 pack,STREAM-01
20,ROKU-STD,Streaming Device,electronics,Streaming,16.99,Anheuser-Busch,12 pack,ROKU-STD
21,SOUP-CAN,Soup - Canned,Groceries,Canned,1.23,J.M. Smucker,single,SOUP-CAN
22,CNSOUP-01,Canned Soup,GROCERY,NaN,1.19,Generic Supplier,single,CNSOUP-01
23,BREAD-WH,WHITE BREAD,Grocery,Bread,1.53,Procter & Gamble,24-pack,BREAD-WH
24,WHITEBREAD,WHITE BREAD,grocery,Bread,1.12,Sara Lee,24 pack,WHITEBREAD
25,PB-16,PEANUT BUTTER,GROCERY,Peanut,1.36,Hasbro,bundle,PB-16
26,PNUTBTR-16,Peanut Butter,GROCERY,Peanut,1.94,Sara Lee,1-pack,PNUTBTR-16
27,CNDL-EM,Candles (Emergency),EMERGENCY,Candles,3.81,Frito-Lay,1 pack,CNDL-EM
28,CANDLE-EMRG,Emergency Candles,EMERGENCY,Candles,3.43,Roku Inc,24pk,CANDLE-EMRG
29,FAID-01,First-Aid Kit,health,First,6.90,Anheuser-Busch,4 pack,FAID-01
30,FIRSTAID-KIT,First Aid Kit,health,NaN,7.85,J.M. Smucker,4 pack,FIRSTAID-KIT
31,CHRG-PORT,PORTABLE CHARGER,ELECTRONICS,NaN,11.99,Georgia-Pacific,single,CHRG-PORT
32,PORTCHARGER,Portable Phone Charger,ELECTRONICS,Portable,15.03,Johnson & Johnson,12 pack,PORTCHARGER
33,CHIPS-VP,Variety Pack - Chips,snacks,Chips,4.03,Frito-Lay,single,CHIPS-VP
34,CHIPVARIETY,Chips Variety Pack,Snacks,Chips,4.11,Generic Supplier,4-pack,CHIPVARIETY
35,PTOWEL-6,Paper Towels,household,Paper,3.85,Campbell's,4 pack,PTOWEL-6
36,PAPERTOWEL6,Paper Towels,HOUSEHOLD,Paper,5.09,Georgia-Pacific,12-pack,PAPERTOWEL6
37,TP-12,TOILET PAPER 12PK,household,Toilet,5.58,Campbell's,1 pack,TP-12
38,TOILETPAPER12,Toilet Paper 12-Roll,Household,Toilet,5.75,J.M. Smucker,24-pack,TOILETPAPER12
39,DIAP-S3,Baby Diapers - Size 3,baby,Diapers,14.40,Procter & Gamble,single,DIAP-S3
40,DIAPERS-3,DIAPERS SZ 3,Baby Products,Diapers,13.59,Generic Supplier,6 pack,DIAPERS-3
41,BFORM-01,Infant Formula,Baby,Baby,18.87,Procter & Gamble,4-pack,BFORM-01
42,BABYFORMULA,Baby Formula,Baby,NaN,18.25,Sara Lee,6 pack,BABYFORMULA
43,TARP-HD,Heavy Duty Tarp,Emergency,NaN,11.90,J.M. Smucker,12 pack,TARP-HD
44,HDTARP-01,TARP - HEAVY DUTY,emergency,Tarp,NaN,J.M. Smucker,24pk,HDTARP-01

### Q4 — Normalize `category`

Strip and title-case, then show the distinct values before and after with counts. Note any pair that is still two labels for one thing — `Breakfast` and `Breakfast Foods` are not the same string but they are the same category.

In [5]:
# TODO
print("Before:", cat["category"].nunique(), "distinct categories")
print(cat["category"].value_counts())

cat["category"] = cat["category"].str.strip().str.title()

print("After:", cat["category"].nunique(), "distinct categories")
print(cat["category"].value_counts())

Before: 27 distinct categories
category
Emergency              5
Emergency Supplies     3
EMERGENCY              3
ENTERTAINMENT          3
GROCERY                3
Breakfast              2
entertainment          2
household              2
ELECTRONICS            2
health                 2
Baby                   2
Electronics            1
ALCOHOL                1
Alcoholic Beverages    1
breakfast              1
Breakfast Foods        1
Groceries              1
Grocery                1
electronics            1
snacks                 1
grocery                1
HOUSEHOLD              1
Snacks                 1
Household              1
baby                   1
Baby Products          1
emergency              1
Name: count, dtype: int64
After: 15 distinct categories
category
Emergency              9
Entertainment          5
Grocery                5
Electronics            4
Household              4
Emergency Supplies     3
Breakfast              3
Baby                   3
Snacks                 2
Health                 2
Breakfast Foods        1
Alcohol                1
Alcoholic Beverages    1
Groceries              1
Baby Products          1
Name: count, dtype: int64

### Q5 — Find the fragmentation you have not spotted yet

Hand-scanning a catalog does not scale. **TODO:** build a candidate list programmatically — normalize each product name (lowercase, strip punctuation, sort the words) and group by that, then show any group holding more than one SKU.

This is the workflow from Monday's lecture, and it is how you will actually approach the full catalog on the midterm.

In [6]:
# TODO

import re

def normalize_name(name):
    name = re.sub(r"[^\w\s]", " ", name.lower())

    words = sorted(name.split())

    return " ".join(words)

cat["normalized_name"] = cat["product_name"].apply(normalize_name)

groups = cat.groupby("normalized_name").agg(skus=("sku", list),names=("product_name", list),sku_count=("sku", "nunique"))

print(groups)

more_than_one_groups = groups[groups['sku_count'] > 1]

print(more_than_one_groups)

                                                         skus  \
normalized_name
12 paper roll toilet                          [TOILETPAPER12]
12pk paper toilet                                     [TP-12]
24 beer light pack                        [BEER-24, LTBEER24]
24 bottled pack water                             [WATER24PK]
24 pack water                                      [WTR_24PK]
24pk bottled water                                   [WTR-24]
3 baby diapers size                                 [DIAP-S3]
3 diapers sz                                      [DIAPERS-3]
4 aa batteries pack                    [BAT-AA4, BATT_AA_4PK]
4pk aa batteries                                   [BATT-100]
aid first kit                         [FAID-01, FIRSTAID-KIT]
baby formula                                    [BABYFORMULA]
board game monopoly         [BG-MONO, MONOPOLY-01, GAME-MONO]
bread white                            [BREAD-WH, WHITEBREAD]
butter peanut                             [PB-16, PNUTBTR-16]
candles emergency                      [CNDL-EM, CANDLE-EMRG]
canned soup                             [SOUP-CAN, CNSOUP-01]
cards playing                        [CARDS-01, PLAYCARD-STD]
charger phone portable                          [PORTCHARGER]
charger portable                                  [CHRG-PORT]
chips pack variety                    [CHIPS-VP, CHIPVARIETY]
device streaming                                   [ROKU-STD]
duty heavy tarp                          [TARP-HD, HDTARP-01]
flashlight led                          [FLASH-01, LED-FLASH]
formula infant                                     [BFORM-01]
paper towels                          [PTOWEL-6, PAPERTOWEL6]
pop strawberry tart                              [SKU#459812]
pop strawberry tarts    [PT-12, POPTART-STRAW, PT_STRAWBERRY]
roku stick streaming                              [STREAM-01]

                                                                    names  \
normalized_name
12 paper roll toilet                               [Toilet Paper 12-Roll]
12pk paper toilet                                     [TOILET PAPER 12PK]
24 beer light pack           [Light Beer (24-pack), Light Beer (24-pack)]
24 bottled pack water                             [Bottled Water 24-Pack]
24 pack water                                           [Water - 24 Pack]
24pk bottled water                                   [BOTTLED WATER 24PK]
3 baby diapers size                               [Baby Diapers - Size 3]
3 diapers sz                                               [DIAPERS SZ 3]
4 aa batteries pack            [AA Batteries 4-Pack, AA Batteries 4-Pack]
4pk aa batteries                                       [BATTERIES AA 4PK]
aid first kit                              [First-Aid Kit, First Aid Kit]
baby formula                                               [Baby Formula]
board game monopoly     [Monopoly Board Game, Monopoly Board Game, Boa...
bread white                                    [WHITE BREAD, WHITE BREAD]
butter peanut                              [PEANUT BUTTER, Peanut Butter]
candles emergency                [Candles (Emergency), Emergency Candles]
canned soup                                  [Soup - Canned, Canned Soup]
cards playing                              [Playing Cards, PLAYING CARDS]
charger phone portable                           [Portable Phone Charger]
charger portable                                       [PORTABLE CHARGER]
chips pack variety             [Variety Pack - Chips, Chips Variety Pack]
device streaming                                       [Streaming Device]
duty heavy tarp                      [Heavy Duty Tarp, TARP - HEAVY DUTY]
flashlight led                           [FLASHLIGHT LED, FLASHLIGHT LED]
formula infant                                           [Infant Formula]
paper towels                                 [Paper Towels, Paper Towels]
pop strawberry tart                                 [Strawberry Pop-Tart]
pop strawberry tarts    [pop-tarts strawberry, Pop-Tarts Strawberry, p...
roku stick streaming                               [Roku Streaming Stick]

                        sku_count
normalized_name
12 paper roll toilet            1
12pk paper toilet               1
24 beer light pack              2
24 bottled pack water           1
24 pack water                   1
24pk bottled water              1
3 baby diapers size             1
3 diapers sz                    1
4 aa batteries pack             2
4pk aa batteries                1
aid first kit                   2
baby formula                    1
board game monopoly             3
bread white                     2
butter peanut                   2
candles emergency               2
canned soup                     2
cards playing                   2
charger phone portable          1
charger portable                1
chips pack variety              2
device streaming                1
duty heavy tarp                 2
flashlight led                  2
formula infant                  1
paper towels                    2
pop strawberry tart             1
pop strawberry tarts            3
roku stick streaming            1
                                                       skus  \
normalized_name
24 beer light pack                      [BEER-24, LTBEER24]
4 aa batteries pack                  [BAT-AA4, BATT_AA_4PK]
aid first kit                       [FAID-01, FIRSTAID-KIT]
board game monopoly       [BG-MONO, MONOPOLY-01, GAME-MONO]
bread white                          [BREAD-WH, WHITEBREAD]
butter peanut                           [PB-16, PNUTBTR-16]
candles emergency                    [CNDL-EM, CANDLE-EMRG]
canned soup                           [SOUP-CAN, CNSOUP-01]
cards playing                      [CARDS-01, PLAYCARD-STD]
chips pack variety                  [CHIPS-VP, CHIPVARIETY]
duty heavy tarp                        [TARP-HD, HDTARP-01]
flashlight led                        [FLASH-01, LED-FLASH]
paper towels                        [PTOWEL-6, PAPERTOWEL6]
pop strawberry tarts  [PT-12, POPTART-STRAW, PT_STRAWBERRY]

                                                                  names  \
normalized_name
24 beer light pack         [Light Beer (24-pack), Light Beer (24-pack)]
4 aa batteries pack          [AA Batteries 4-Pack, AA Batteries 4-Pack]
aid first kit                            [First-Aid Kit, First Aid Kit]
board game monopoly   [Monopoly Board Game, Monopoly Board Game, Boa...
bread white                                  [WHITE BREAD, WHITE BREAD]
butter peanut                            [PEANUT BUTTER, Peanut Butter]
candles emergency              [Candles (Emergency), Emergency Candles]
canned soup                                [Soup - Canned, Canned Soup]
cards playing                            [Playing Cards, PLAYING CARDS]
chips pack variety           [Variety Pack - Chips, Chips Variety Pack]
duty heavy tarp                    [Heavy Duty Tarp, TARP - HEAVY DUTY]
flashlight led                         [FLASHLIGHT LED, FLASHLIGHT LED]
paper towels                               [Paper Towels, Paper Towels]
pop strawberry tarts  [pop-tarts strawberry, Pop-Tarts Strawberry, p...

                      sku_count
normalized_name
24 beer light pack            2
4 aa batteries pack           2
aid first kit                 2
board game monopoly           3
bread white                   2
butter peanut                 2
candles emergency             2
canned soup                   2
cards playing                 2
chips pack variety            2
duty heavy tarp               2
flashlight led                2
paper towels                  2
pop strawberry tarts          3

### Q6 — Prove the mapping is safe

**TODO:** assert that applying your mapping produced no nulls in the canonical column and did not change the number of rows. Consolidation renames; it never adds or removes.

In [7]:
# TODO
assert cat["canonical_sku"].notna().all()

assert len(cat) == cat_length

print("All checks passed")

All checks passed

### Write-up

**a)** Name two product families beyond Pop-Tarts that appear fragmented, and how you would group them.

**b)** Where does consolidation stop being a data-cleaning task and become a business decision? Give one example from this catalog where you genuinely are not sure, and say who you would ask.

a) Two product families that appear to be fragmented are beers and 4 AA batteries. Beer has two different SKUs (BEER-24, LTBEER24) and AA batteries have two different SKUs (BAT-AA4, BATT_AA_4PK) for the same exact product. I would group them by a canonical SKU similar to the Pop Tarts while also maintaining the original.

b) Consolidation stops being a data-cleaning task and more of a business decision when they have differences that are related to how they're sold. For example, with strawberry pop tarts, they come in 6-pack and 4-pack variations so whether they should be grouped under the same SKU is a decision I wouldn't be sure of. To determine this, I would probably ask whoever handles inventory to determine whether this should be counted under one canonical SKU or separate based on quantity.